project_id = "lbrwdmnctmivgrsgdpqj"

[functions.update-prices]
verify_jwt = false

[functions.simulate-confirmations]
verify_jwt = false

[functions.generate-deposit-address]
verify_jwt = false

[functions.get-deposit-address]
verify_jwt = false
